---
- hosts: all
  tasks:
    - name: build image
      docker_image:
      force: yes
      name: glassfish
      path: .
      rm: yes
      state: present
      tag: latest
  register: image_build
    - name: install glassfish
      docker_container:
        name: glassfish
        image: glassfish:latest
        ports:
          - 4848:4848
          - 81:8080
          - 8081:8081
        recreate: yes
