---
- hosts: all
  tasks:
    - name: build image
      docker_image:
        force: yes
        name: glassfish
        path: /
        rm: yes
        state: present
        path: /home/tmp/
    - name: install glassfish
      docker_container:
        name: glassfish
        image: glassfish
        ports:
          - 4848:4848
          - 81:8080
          - 8081:8081
        recreate: yes
